spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test
    username: sa
    password:
    initialization-mode: always
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    jp:
      demo:
        infrastructure:
          mapper: debug
